import type { Question } from "./types";

export const QUESTIONS: Question[] = [
  {
    id: "teamSize",
    category: "Team",
    label: "Hvor mange selgere har dere i dag?",
    help: "Inkluder alle som aktivt selger, også deltidsselgere.",
    placeholder: "f.eks. 4",
    type: "number",
    suffix: "selgere",
  },
  {
    id: "tenure",
    category: "Team",
    label: "Hva er gjennomsnittlig fartstid for selgerne i selskapet?",
    help: "Antall år i nåværende selskap, ikke total salgserfaring.",
    placeholder: "f.eks. 3",
    type: "number",
    suffix: "år",
    slider: { min: 0, max: 20, step: 1 },
  },
  {
    id: "avgAge",
    category: "Team",
    label: "Hva er gjennomsnittsalderen på selgerteamet?",
    help: "Et omtrentlig tall holder fint.",
    placeholder: "f.eks. 32",
    type: "number",
    suffix: "år",
    slider: { min: 18, max: 65, step: 1 },
  },
  {
    id: "icp",
    category: "Strategi",
    label: "Beskriv deres ideelle kundeprofil (ICP).",
    help: "Bransje, selskapsstørrelse og hvem som tar beslutningen.",
    placeholder: "f.eks. SaaS-selskaper med 20–100 ansatte, beslutningstaker er salgsdirektør",
    type: "text",
  },
  {
    id: "meetingsPerRep",
    category: "Pipeline",
    label: "Hvor mange salgsmøter holder hver selger i snitt per måned?",
    help: "Inkluder demo, discovery, closing-møter og lignende.",
    placeholder: "f.eks. 8",
    type: "number",
    suffix: "møter / mnd",
  },
  {
    id: "closeRate",
    category: "Pipeline",
    label: "Hva er gjennomsnittlig closing rate fra møte til signert deal?",
    help: "Vet dere ikke eksakt? Et estimat holder fint.",
    placeholder: "f.eks. 22",
    type: "number",
    suffix: "%",
    slider: { min: 0, max: 100, step: 1 },
  },
  {
    id: "dealSize",
    category: "Økonomi",
    label: "Hva er gjennomsnittlig avtalestørrelse?",
    help: "Årlig kontraktsverdi (ACV). Har dere månedlige abonnement, oppgi månedlig beløp.",
    placeholder: "f.eks. 85 000",
    type: "number",
    prefix: "kr",
  },
  {
    id: "salesCycle",
    category: "Pipeline",
    label: "Hva er gjennomsnittlig sales cycle?",
    help: "Tid fra første møte til signert deal.",
    placeholder: "f.eks. 30",
    type: "number",
    suffix: "dager",
    slider: { min: 1, max: 365, step: 1 },
  },
  {
    id: "crm",
    category: "Verktøy",
    label: "Hvilket CRM bruker dere, og hvor disiplinert føres data der?",
    help: "Velg verktøy og beskriv gjerne bruken kort.",
    placeholder: "",
    type: "select",
    options: [
      "HubSpot",
      "Pipedrive",
      "Salesforce",
      "SuperOffice",
      "Microsoft Dynamics",
      "Excel / regneark",
      "Ingen",
      "Annet",
    ],
  },
  {
    id: "coldOutreach",
    category: "Team",
    label: "Hvor mye cold outreach gjør selgerne selv i dag?",
    help: "Fordel gjerne på telefon, e-post og LinkedIn.",
    placeholder: "f.eks. 10 kalde samtaler, 20 LinkedIn-meldinger og 30 e-poster per uke per selger",
    type: "text",
  },
  {
    id: "proposals",
    category: "Pipeline",
    label: "Hvor mange tilbud sender dere i snitt per måned, og hva er total pipeline value akkurat nå?",
    help: "Omtrentlige tall holder.",
    placeholder: "f.eks. 12 tilbud / mnd, pipeline på ca. 2,4 mill kr",
    type: "text",
  },
  {
    id: "leadSources",
    category: "Pipeline",
    label: "Hvor får dere leads fra i dag?",
    help: "Velg alle som er relevante og ranger gjerne etter volum.",
    placeholder: "",
    type: "multiselect",
    options: [
      "Inbound (nettside, innhold)",
      "Outbound (kald kontakt)",
      "Anbefalinger / referrals",
      "Partnere",
      "Events / messer",
      "Annet",
    ],
  },
  {
    id: "salesProcess",
    category: "Strategi",
    label: "Har dere en definert salgsprosess eller playbook?",
    help: "Send gjerne en kort beskrivelse eller lenke hvis dere har det.",
    placeholder: "Beskriv prosessen kort, eller lim inn en lenke",
    type: "boolean",
  },
  {
    id: "conversionTracking",
    category: "Strategi",
    label: "Hvordan måler dere konvertering gjennom salgstrakten?",
    help: "Fra MQL til SQL til tilbud til signert — hvilke tall følger dere med på?",
    placeholder: "f.eks. Vi rapporterer SQL og close rate månedlig i HubSpot",
    type: "text",
  },
  {
    id: "bottleneck",
    category: "Strategi",
    label: "Hva er den største flaskehalsen i salget akkurat nå?",
    help: "Beskriv med egne ord — det er ofte her de raskeste gevinstene finnes.",
    placeholder: "f.eks. For få kvalifiserte møter, eller lang tid fra tilbud til svar",
    type: "text",
  },
];


export const SKIP_LABEL = "Vet ikke / Har ikke tall på det";
